### ISSUE TITLE
Visor de Personajes en Realidad Aumentada

### ISSUE THREAD

**Issue by ricopozasmarcial** [VendoOpelCorsa/AmongCars#11]
Marcos y yo estaremos trabajando en una escena que nos permita visualizar a Jacinto y compañía en Realidad Aumentada con diferentes cartas. Esta opción estará disponible desde la pantalla de inicio del juego

**Comment by marcosmatilla** [comment]
Jacinto disponible, seguimos con los compañeros y distintos bailes. Poco a poco haciendo uso de Mixamo para crear las animaciones.
