### ISSUE TITLE
Nivel de cordura

### ISSUE THREAD

**Issue by sofimrtn** [VendoOpelCorsa/AmongCars#19]
Se ha implementado el nivel de cordura. De momento solo se resta cuando se pierde al Simón.

**Comment by marcosmatilla** [comment]
@ricopozasmarcial cuando gana el laberinto, el nivel de cordura se tiene que poner al máximo

**Comment by marcosmatilla** [comment]
En la clase Cordura.cs hay un método recuperarCordura() para que puedas usarlo

**Comment by marcosmatilla** [comment]
En el script del laberinto, un atributo _private GameObject player;_ para que le asignes el player.
Y en el momento en el que se gana el laberinto: _player.SendMessage("RecuperarCordura");_

**Comment by sofimrtn** [comment]
done
