### ISSUE TITLE
New ideas for final sprint

### ISSUE THREAD

**Issue by ricopozasmarcial** [VendoOpelCorsa/AmongCars#23]
Tenemos claro que hay que iterar y mejorar en lo ya establecido en el sprint 3 pero estuve pensando en algunas funcionalidades menores que podrían aportar mejoras en la calidad general del proyecto tales como un menú de pausa y una opcion en el menu que indique los controles in-game

**Comment by marcosmatilla** [comment]
Alguna propuesta más?

**Comment by ricopozasmarcial** [comment]
El menú de pausa con ese esquema de controles está implementado, falta hacer el correspondiente testing en Android pero mi dispositivo crashea con la build actual quizás es problema de mi movil
