### ISSUE TITLE
Interacción entre personajes

### ISSUE THREAD

**Issue by sofimrtn** [VendoOpelCorsa/AmongCars#9]
Incluir dentro del proyecto Unity los diálogos entre personajes siguiendo la narrativa especificada en #5

**Comment by sofimrtn** [comment]
En este [commit](https://github.com/VendoOpelCorsa/AmongCars/commit/8b8df09ed084d19fdf360dfe9255cf6e88ca2683) se ha implementado la primera interacción con Turquesa y se han colocado todos los personajes en la escena.

**Comment by SaraGarcia13** [comment]
Con este [commit](https://github.com/VendoOpelCorsa/AmongCars/commit/e0afa708d237b7ee1e1a46700247b4898321c260) todos los personajes tienen sus correspondientes diálogos, la primera ronda.

**Comment by SaraGarcia13** [comment]
Ahora Jacinto si se acerca a Verde, interactúa con él, [commit](https://github.com/VendoOpelCorsa/AmongCars/commit/78c791563b77729a5a1260e1361e0a511a0f7105)

**Comment by SaraGarcia13** [comment]
Ahora hay dos rondas de interacción, cada vez que te acerques el personaje dirá una cosa distinta
